// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UretimOperasyonBildirimleri.Models;

namespace UretimOperasyonBildirimleri.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("UretimOperasyonBildirimleri.Models.bildirim", b =>
                {
                    b.Property<int>("IsNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Baslangic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Bitis")
                        .HasColumnType("TEXT");

                    b.Property<string>("DurusNedeni")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToplamSure")
                        .HasColumnType("TEXT");

                    b.HasKey("IsNo");

                    b.ToTable("bildirims");
                });

            modelBuilder.Entity("UretimOperasyonBildirimleri.Models.duruslar", b =>
                {
                    b.Property<int>("DurusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Baslangic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Bitis")
                        .HasColumnType("TEXT");

                    b.Property<string>("DurusNededi")
                        .HasColumnType("TEXT");

                    b.HasKey("DurusId");

                    b.ToTable("duruslars");
                });
#pragma warning restore 612, 618
        }
    }
}
